# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: ./
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge
paginate : 5
paginate_path: "page:num"

# SEO settings
title: Gechmind
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"

# Site settings
url: http://gechmind.com
baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : Gechmind
  job       : Frontend Engineer
  bio       : "未知之事，未知之势，未知之世"
  email     : qlwy76cc1991@gmail.com
  url       : http://gechmind.com
  github    : https://github.com/Gechmind
  twitter   : https://twitter.com/cc76cz
  facebook  : https://www.facebook.com/gechmind.cc

# google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/dotX

# comments
disqus_shortname: "gechmind"
